// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	worker_grpc "github.com/Qu1nel/YaLyceum-GoProject-Final/proto/gen/worker"
)

// WorkerServiceClientMock is an autogenerated mock type for the WorkerServiceClient type
type WorkerServiceClientMock struct {
	mock.Mock
}

// CalculateOperation provides a mock function with given fields: ctx, in, opts
func (_m *WorkerServiceClientMock) CalculateOperation(ctx context.Context, in *worker_grpc.CalculateOperationRequest, opts ...grpc.CallOption) (*worker_grpc.CalculateOperationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CalculateOperation")
	}

	var r0 *worker_grpc.CalculateOperationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *worker_grpc.CalculateOperationRequest, ...grpc.CallOption) (*worker_grpc.CalculateOperationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *worker_grpc.CalculateOperationRequest, ...grpc.CallOption) *worker_grpc.CalculateOperationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker_grpc.CalculateOperationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *worker_grpc.CalculateOperationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkerServiceClientMock creates a new instance of WorkerServiceClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerServiceClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerServiceClientMock {
	mock := &WorkerServiceClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
